version: '3.1'

services:
        db0:
           image: mysql:5.7
           volumes:
                   - mysql_storage:/var/lib/mysql:rw
           restart: always
           ports:
                   - 3308:3306
           environment:
                   - MYSQL_ROOT_PASSWORD=rhel
                   - MYSQL_USERNAME=doc
                   - MYSQL-PASSWORD=rhel
                   - MYSQL_DATABASE=mydb
        db1:
               image: mysql:8.0.2
               volumes:
                       - mysql_storage_new:/var/lib/mysql:rw
               ports:
                       - 3309:3306
               environment:
                       - MYSQL_ROOT_PASSWORD=rhel1
                       - MYSQL_USERNAME=doc1
                       - MYSQL-PASSWORD=rhel1
                       - MYSQL_DATABASE=mydb1

        db2:
                image: postgres
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgresl
                        - POSRGRES_DB=mydb2
        db3:
                image: phpmyadmin/phpmyadmin
                container_name: phpmyadmin1
                environment:
                        - PMA_HOST:mysql
                        - MYSQL_ROOT_PASSWORD=rhel

                restart: always
                depends_on:
                        - db2
                ports:
                        - 8081:8080
        db5:
                image: adminer
                ports:
                        - 8082:8080

volumes:
        mysql_storage:
        mysql_storage_new:


